### ISSUE TITLE
ペイロードの取得と表示部分の修正

### ISSUE THREAD

**Issue by natsumo** [NIFCLOUD-mbaas/SwiftPayloadApp_iOS10#11]
現在以下画像のように、取得したペイロードを素のAnyHashble形式で表示していると思います。
（画像のapsの所を参照）

<img width="300px" src="https://user-images.githubusercontent.com/16663720/86070030-908a0500-bab6-11ea-9063-86243c95f1fb.png"/>

こちら、表示前に *JSON* 形式に変換して表示するよう修正をお願いします。

また、修正後、下記内容にて動作検証のうえ、↑の画面キャプチャでaps部分がJSON形式になった者をこのissueに添付いただけますでしょうか。
https://github.com/NIFCLOUD-mbaas/SwiftPayloadApp_iOS10#%E3%83%9A%E3%82%A4%E3%83%AD%E3%83%BC%E3%83%89%E3%83%87%E3%83%BC%E3%82%BF%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6

よろしくお願いします。

**Comment by vfa-trucldt** [comment]
>また、修正後、下記内容にて動作検証のうえ、↑の画面キャプチャでaps部分がJSON形式になった者をこのissueに添付いただけますでしょうか。

画像を添付致します。

<img alt="" width="300px" src="https://user-images.githubusercontent.com/38413171/86198269-69e4d080-bb81-11ea-9c01-afec5d228998.PNG">
